version: "3"

services:
  spring-sample-service:
    container_name: spring-sample-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sample

  mariadb:
    image: mariadb
    container_name: mariadb-container
    restart: always
    ports:
      - "3306:3306"
    entrypoint:
      - MARIADB_ROOT_PASSWORD=43214321