server:
  port: 8080


spring:
  ## Profile Setting
  application:
    name: SpringBoot-Sample-Prod
  config:
    activate:
      on-profile: prod

  ## DataBase (MongoDB)
  data:
    mongodb:
      host: mongodb-container
      port: 27017
      database: sample

  ## DataBase (MySQL)
  h2:
    console:
      enabled: false
      path: /h2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://mariadb-container:3306/sample
    username: root
    password: 43214321

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        naming:
          physical-strategy = org.hibernate.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    generate-ddl: true

# Logging Info
logging:
  level:
    org.springframework: info

springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"